export const bookingContent = {
  statusBar: {
    label: "PORTAL DE BILHÉTICA DIGITAL",
    sessionLabel: "SESSÃO ENCRIPTADA 256-BIT (EMIS-SECURE)",
    sessionBlock: "BLOQUEIO TEMPORÁRIO:",
  },
  steps: [
    { num: "01", label: "Rota & Horário", done: false, current: false },
    { num: "02", label: "Assento & Autocarro", done: false, current: true },
    { num: "03", label: "Passageiro & Bagagem", done: false, current: false },
    { num: "04", label: "Pagamento EMIS", done: false, current: false },
  ],
  stepLabels: ["1. Rota & Horário", "2. Assento & Autocarro", "3. Passageiro & Bagagem", "4. Pagamento"],
  viagem: {
    ref: "MANIFESTO RE-2410-LUA-BEN",
    viaturaLabel: "VIATURA OFICIAL RE-014",
    viaturaDesc: "Marcopolo G7 Scania K",
    viaturaSvc: "Executivo VIP Climatizado (Wi-Fi 5G & Tomadas)",
    origemLabel: "TERMINAL LUANDA (HO CHI MINH)",
    destinoLabel: "TERMINAL BENGUELA (INDEP.)",
    partida: "06h30",
    chegada: "13h30",
    data: "24 OUTUBRO 2026",
    duracao: "~ 7H00 ESTIMADAS",
    tipo: "DIRETO / SEM ESCALA",
    preco: "18.000 KZ",
    bagagem: "Bagagem 25kg + Bebida Inclusa",
  },
  seatMap: {
    header: "MAPA TÁTICO DA CABINE // 52 LUGARES",
    layoutBadge: "LAYOUT 2 x 2 STANDARD",
    columns: ["JAN (A)", "COR (B)", "CORREDOR", "COR (C)", "JAN (D)"],
    legend: [
      { label: "Disponível", style: "available" },
      { label: "Selecionado", style: "selected" },
      { label: "Ocupado", style: "occupied" },
      { label: "Frente / Prioritário", style: "priority" },
    ],
    driverCabin: "CABINE // CAP. MATEUS NDALA",
    driverBadge: "VOLANTE",
    doorLabel: "PORTA EMBARQUE",
    rearAmenities: [
      { icon: "wc", label: "WC CLIMATIZADO" },
      { icon: "local_cafe", label: "MINIBAR EXECUTIVO" },
    ],
    rows: 13,
    cols: 4,
    occupied: ["01", "02", "03", "04", "11", "12", "16", "21", "22", "29"],
    priority: ["01", "02", "03"],
    exitRow: 6,
  },
  fleetSpecs: {
    header: "FICHA DA VIATURA EM OPERAÇÃO",
    model: "SCANIA K-360 IB 4x2",
    specs: [
      { label: "SISTEMA SEGURANÇA", value: "ESP + Retarder Hidráulico" },
      { label: "MONITORAMENTO", value: "Telemetria GPS Live 24/7" },
      { label: "CLIMATIZAÇÃO", value: "AC Digital Purificado" },
      { label: "ENTRETENIMENTO", value: "Streaming Wi-Fi Rosalina" },
    ],
  },
  passenger: {
    header: "PASSAGEIRO 01 // LUGAR 14",
    seatBadge: "ASSENTO JANELA",
    fields: [
      { label: "Nome Completo (Conforme Documento)", placeholder: "Manuel Bartolomeu Kipapa", required: true },
      { label: "Nº de B.I. ou Passaporte", placeholder: "004839201LA042", required: true },
    ],
    phonePrefix: "+244",
    phonePlaceholder: "923 884 190",
    emailPlaceholder: "manuel.kipapa@angola-logistica.ao",
    seatNote: "Regra de Reserva Instantânea: Limite máximo de 4 bilhetes por emissão online.",
  },
  baggage: {
    items: [
      { label: "Bagagem Padrão Rosalina", desc: "1x Mala no porão até 25kg + 1x Mala de mão 5kg", price: "INCLUSO", defaultChecked: true, readonly: true },
      { label: "Volume Extra no Porão (+15kg)", desc: "Capacidade adicional para bagagem volumosa", price: "+ 4.500 KZ", defaultChecked: false },
      { label: "Seguro Rosalina Protegida", desc: "Cobertura médica rodoviária & extravio de pertences", price: "+ 1.200 KZ", defaultChecked: true },
    ],
  },
  payment: {
    header: "PAGAMENTO SEGURO // ANGOLA",
    emvBadge: "EMIS VERIFIED",
    methods: [
      { id: "multicaixa", label: "MULTICAIXA EXPRESS", sub: "INSTANTÂNEO", icon: "payments", active: true },
      { id: "referencia", label: "REFERÊNCIA MULTICAIXA (ATM / INTERNET)", sub: "", icon: "pin", active: false },
      { id: "cartao", label: "CARTÃO BANCÁRIO (VISA / MASTERCARD)", sub: "", icon: "credit_card", active: false },
    ],
    breakdown: [
      { label: "TARIFA BASE (LUGAR 14 - EXECUTIVO)", value: "18.000 KZ" },
      { label: "SEGURO DE VIAGEM PROTEGIDA", value: "1.200 KZ" },
      { label: "TAXA EMISSÃO DIGITAL (WEB)", value: "0 KZ (ISENTO)" },
      { label: "IVA RODOVIÁRIO (INCLUÍDO)", value: "14% APLICADO" },
    ],
    totalLabel: "TOTAL LIQUIDAÇÃO",
    totalCurrency: "MOEDA NACIONAL (KZ)",
    total: "19.200 KZ",
    buttonLabel: "FINALIZAR COMPRA & EMITIR E-TICKET",
    buttonNote: "AO CLICAR, AUTORIZA O DÉBITO IMEDIATO VIA MULTICAIXA EXPRESS.",
    trustSeals: [
      "Certificado EMV homologado pela EMIS (Angola).",
      "Cancelamento gratuito ou reagendamento até 2h antes do embarque.",
      "Envio instantâneo do bilhete PDF com QR-Code para WhatsApp e E-mail.",
    ],
  },
  routes: [
    {
      id: "RE-014",
      origem: "LUANDA",
      destino: "BENGUELA",
      partida: "06h30",
      chegada: "13h30",
      duracao: "7h00",
      tipo: "Executivo VIP",
      preco: "18.000",
      prefix: "RE-014",
      viatura: "Marcopolo G7 Scania K",
      servico: "Executivo VIP Climatizado (Wi-Fi 5G & Tomadas)",
    },
    {
      id: "RE-089",
      origem: "LUANDA",
      destino: "HUAMBO",
      partida: "08h00",
      chegada: "15h15",
      duracao: "7h15",
      tipo: "Expresso",
      preco: "16.500",
      prefix: "RE-089",
      viatura: "Scania K410",
      servico: "Expresso Leito Total",
    },
    {
      id: "RE-105",
      origem: "BENGUELA",
      destino: "LOBITO",
      partida: "14h00",
      chegada: "16h40",
      duracao: "2h40",
      tipo: "Shuttle",
      preco: "5.000",
      prefix: "RE-105",
      viatura: "Volvo B11R",
      servico: "Interurbano Regular",
    },
  ],
};
