export const bookingContent = {
  statusBar: {
    label: "PORTAL DE BILHÉTICA DIGITAL",
    sessionLabel: "SESSÃO ENCRIPTADA 256-BIT (EMIS-SECURE)",
    sessionBlock: "BLOQUEIO TEMPORÁRIO:",
  },
  steps: [
    { num: "01", label: "Rota & Horário", done: false, current: false },
    { num: "02", label: "Assento & Autocarro", done: false, current: true },
    { num: "03", label: "Passageiro & Bagagem", done: false, current: false },
    { num: "04", label: "Pagamento EMIS", done: false, current: false },
  ],
  stepLabels: ["1. Rota & Horário", "2. Assento & Autocarro", "3. Passageiro & Bagagem", "4. Pagamento"],
  viagem: {
    ref: "VOLTAS RE-2026-LUA-ZAN",
    viaturaLabel: "VIATURA VOLTAS LUANDA",
    viaturaDesc: "Toyota / Volkswagen / Yutong",
    viaturaSvc: "Transporte Urbano Climatizado",
    origemLabel: "TERMINAL LUANDA (HO CHI MINH)",
    destinoLabel: "ZANGO 0 — VILA DE VIANA",
    partida: "07h00",
    chegada: "07h45",
    data: "SEGUNDA A SEXTA",
    duracao: "~ 45 MIN",
    tipo: "URBANO // PARAGENS MÚLTIPLAS",
    preco: "500 KZ",
    bagagem: "Bagagem 10kg incluída",
  },
  seatMap: {
    header: "MAPA TÁTICO DA CABINE // VOLTAS URBANO",
    layoutBadge: "LAYOUT 2 x 2 STANDARD",
    columns: ["JAN (A)", "COR (B)", "CORREDOR", "COR (C)", "JAN (D)"],
    legend: [
      { label: "Disponível", style: "available" },
      { label: "Selecionado", style: "selected" },
      { label: "Ocupado", style: "occupied" },
      { label: "Frente / Prioritário", style: "priority" },
    ],
    driverCabin: "CABINE // CAPITAO DA VIATURA",
    driverBadge: "VOLANTE",
    doorLabel: "PORTA EMBARQUE",
    rearAmenities: [
      { icon: "wc", label: "WC CLIMATIZADO" },
      { icon: "local_cafe", label: "ÁGUA INCLUÍDA" },
    ],
    rows: 13,
    cols: 4,
    occupied: ["01", "02", "03", "04", "11", "12", "16", "21", "22", "29"],
    priority: ["01", "02", "03"],
    exitRow: 6,
  },
  fleetSpecs: {
    header: "FICHA DA VIATURA EM OPERAÇÃO",
    model: "TOYOTA / VOLKSWAGEN / YUTONG",
    specs: [
      { label: "SISTEMA SEGURANÇA", value: "GPS Live 24/7 + Telemetria" },
      { label: "MONITORAMENTO", value: "Supervisão Central Rosalina" },
      { label: "CLIMATIZAÇÃO", value: "AC Automático" },
      { label: "CAPACIDADE", value: "52 Lugares Sentados" },
    ],
  },
  passenger: {
    header: "PASSAGEIRO 01",
    seatBadge: "ASSENTO JANELA",
    fields: [
      { label: "Nome Completo (Conforme Documento)", placeholder: "Manuel Bartolomeu Kipapa", required: true },
      { label: "Nº de B.I. ou Passaporte", placeholder: "004839201LA042", required: true },
    ],
    phonePrefix: "+244",
    phonePlaceholder: "923 884 190",
    emailPlaceholder: "passageiro@email.ao",
    seatNote: "Limite máximo de 4 bilhetes por emissão online.",
  },
  baggage: {
    items: [
      { label: "Bagagem Padrão Voltas", desc: "1x Mala até 10kg incluída na tarifa", price: "INCLUSO", defaultChecked: true, readonly: true },
      { label: "Volume Extra no Porão (+15kg)", desc: "Capacidade adicional para bagagem volumosa", price: "+ 500 KZ", defaultChecked: false },
      { label: "Seguro Rosalina Protegida", desc: "Cobertura médica rodoviária & extravio", price: "+ 200 KZ", defaultChecked: false },
    ],
  },
  payment: {
    header: "PAGAMENTO SEGURO // ANGOLA",
    emvBadge: "EMIS VERIFIED",
    methods: [
      { id: "multicaixa", label: "MULTICAIXA EXPRESS", sub: "INSTANTÂNEO", icon: "payments", active: true },
      { id: "referencia", label: "REFERÊNCIA MULTICAIXA (ATM / INTERNET)", sub: "", icon: "pin", active: false },
      { id: "cartao", label: "CARTÃO BANCÁRIO (VISA / MASTERCARD)", sub: "", icon: "credit_card", active: false },
    ],
    breakdown: [
      { label: "TARIFA BASE (VOLTAS URBANO)", value: "500 KZ" },
      { label: "SEGURO DE VIAGEM", value: "0 KZ" },
      { label: "TAXA EMISSÃO DIGITAL (WEB)", value: "0 KZ (ISENTO)" },
      { label: "TOTAL A PAGAR", value: "500 KZ" },
    ],
    totalLabel: "TOTAL LIQUIDAÇÃO",
    totalCurrency: "MOEDA NACIONAL (KZ)",
    total: "500 KZ",
    buttonLabel: "FINALIZAR COMPRA & EMITIR E-TICKET",
    buttonNote: "AO CLICAR, AUTORIZA O DÉBITO IMEDIATO VIA MULTICAIXA EXPRESS.",
    trustSeals: [
      "Certificado EMV homologado pela EMIS (Angola).",
      "Cancelamento gratuito ou reagendamento até 2h antes do embarque.",
      "Envio instantâneo do bilhete PDF com QR-Code para WhatsApp e E-mail.",
    ],
  },
  routes: [
    {
      id: "VOL-LU-01",
      origem: "LUANDA",
      destino: "ZANGO 0",
      partida: "06h00",
      chegada: "06h45",
      duracao: "45 min",
      tipo: "Urbano Voltas",
      preco: "500",
      prefix: "VOL-01",
      viatura: "Toyota / Volkswagen",
      servico: "Urbano Regular — Paragens Múltiplas",
    },
    {
      id: "VOL-LU-02",
      origem: "LUANDA",
      destino: "BENFICA",
      partida: "07h00",
      chegada: "07h40",
      duracao: "40 min",
      tipo: "Urbano Voltas",
      preco: "500",
      prefix: "VOL-02",
      viatura: "Yutong / Scania",
      servico: "Urbano Regular — Benfica / Kilamba",
    },
    {
      id: "VOL-LU-03",
      origem: "LUANDA",
      destino: "VIANA",
      partida: "07h30",
      chegada: "08h10",
      duracao: "40 min",
      tipo: "Urbano Voltas",
      preco: "500",
      prefix: "VOL-03",
      viatura: "Volkswagen / Toyota",
      servico: "Urbano Regular — Vila de Viana",
    },
    {
      id: "VOL-BG-01",
      origem: "BENGUELA",
      destino: "BENFICA",
      partida: "06h30",
      chegada: "07h15",
      duracao: "45 min",
      tipo: "Urbano Benguela",
      preco: "400",
      prefix: "BG-01",
      viatura: "Toyota / Mitsubishi",
      servico: "Urbano Benguela — BG5 / Benfica",
    },
    {
      id: "VOL-BG-02",
      origem: "BENGUELA",
      destino: "MIRA MAR",
      partida: "14h00",
      chegada: "14h50",
      duracao: "50 min",
      tipo: "Urbano Benguela",
      preco: "400",
      prefix: "BG-02",
      viatura: "Mitsubishi / Yutong",
      servico: "Urbano Benguela — Benfica / Mira Mar",
    },
    {
      id: "VOL-LB-01",
      origem: "LOBITO",
      destino: "RESTINGA",
      partida: "07h00",
      chegada: "08h00",
      duracao: "1h00",
      tipo: "Urbano Lobito",
      preco: "500",
      prefix: "LB-01",
      viatura: "Toyota / Scania",
      servico: "Urbano Lobito — CB2 / LB4 / Restinga",
    },
  ],
};
