export const contatoContent = {
  subHeader: {
    breadcrumb: ["Início", "Contactos & Localização dos Terminais"],
    badge: "CENTRAL DE RELACIONAMENTO COM O CLIENTE",
    title: "Contactos & Terminais",
    subtitle: "Fale connosco, localize a nossa rede e envie-nos a sua mensagem",
    docBadge: "LINHA DIRETA CORPORATIVA",
    docText: "+244 923 521 224",
    docSub: "DISPONÍVEL 24H / 7 DIAS",
  },
  infoCards: [
    {
      icon: "call",
      title: "Central Telefónica",
      text: "+244 923 521 224",
      sub: "Reservas, informação e assistência 24/7",
      cor: "primary",
    },
    {
      icon: "mark_email_read",
      title: "Email Geral",
      text: "geral@rosalinaexpress.ao",
      sub: "Resposta em menos de 24 horas úteis",
      cor: "tertiary",
    },
    {
      icon: "location_on",
      title: "Sede Corporativa",
      text: "Av. Ho Chi Minh, Luanda",
      sub: "Central Rodoviária — Hub Central 24/7",
      cor: "secondary",
    },
    {
      icon: "schedule",
      title: "Horário Comercial",
      text: "Seg – Sáb: 06h – 20h",
      sub: "Domingos e feriados: 07h – 18h",
      cor: "primary",
    },
  ],
  terminaisTitle: "Rede de Terminais & Balcões",
  terminaisBadge: "LOCALIZE A NOSSA PRESENÇA FÍSICA",
  terminais: [
    {
      cidade: "LUANDA",
      nome: "Terminal Central Rodoviária — Mutamba",
      endereco: "Av. Ho Chi Minh, Central Rodoviária, Luanda",
      horario: "24H / 7 DIAS",
      telefone: "+244 923 521 224",
      cor: "primary",
    },
    {
      cidade: "LUANDA",
      nome: "Terminal de Viana — Área Industrial",
      endereco: "Estrada de Viana, ao lado da ZEE, Viana",
      horario: "05H – 22H",
      telefone: "+244 923 521 225",
      cor: "tertiary",
    },
    {
      cidade: "BENGUELA",
      nome: "Terminal Central de Benguela",
      endereco: "Av. 4 de Abril, Jardim da Ingombota, Benguela",
      horario: "05H – 22H",
      telefone: "+244 923 521 226",
      cor: "secondary",
    },
    {
      cidade: "HUAMBO",
      nome: "Terminal Express do Huambo",
      endereco: "Rua da Missão, Centro, Huambo",
      horario: "05H – 20H",
      telefone: "+244 923 521 227",
      cor: "primary",
    },
    {
      cidade: "LOBITO",
      nome: "Balcão do Lobito",
      endereco: "Av. 25 de Setembro, Lobito",
      horario: "05H – 22H",
      telefone: "+244 923 521 228",
      cor: "tertiary",
    },
    {
      cidade: "LUANDA",
      nome: "Posto de Cacuaco",
      endereco: "Rua principal de Cacuaco, Luanda",
      horario: "06H – 20H",
      telefone: "+244 923 521 229",
      cor: "secondary",
    },
  ],
  faq: {
    badge: "DÚVIDAS FREQUENTES",
    title: "Perguntas & Respostas",
    items: [
      {
        q: "Como posso comprar um bilhete?",
        a: "Pode comprar online na área de Reservas, nos terminais, ou pelos balcões de atendimento da nossa rede. O bilhete também pode ser adquirido diretamente no autocarro, sujeito a disponibilidade.",
      },
      {
        q: "Que documentos são necessários para viajar?",
        a: "Bilhete de identidade ou passaporte em validade é obrigatório para embarque. Menores de 16 anos devem viajar acompanhados ou com autorização notarial.",
      },
      {
        q: "Qual a antecedência máxima para reservar?",
        a: "As reservas abrem com 30 dias de antecedência e fecham 30 minutos antes da partida do autocarro, salvo em dias de alta procura.",
      },
      {
        q: "Como funciona o transporte de encomendas?",
        a: "Entregue a sua encomenda no terminal com a documentação de identificação. A entrega é feita porta-a-porta no destino em até 24h nas rotas principais.",
      },
    ],
  },
  form: {
    badge: "FORMULÁRIO DE CONTACTO",
    title: "Envie-nos a sua Mensagem",
    subjectLabel: "ASSUNTO",
    subjectOptions: ["Reserva de Bilhetes", "Frotas Dedicadas / Corporativo", "Transporte de Cargas", "Reclamação / Sugestão", "Outro assunto"],
    nameLabel: "NOME COMPLETO",
    emailLabel: "EMAIL",
    phoneLabel: "TELEFONE",
    messageLabel: "A SUA MENSAGEM",
    submit: "ENVIAR MENSAGEM",
    privacy: "Ao enviar, aceita a nossa política de privacidade e tratamento de dados.",
    successTitle: "Mensagem enviada com sucesso!",
    successText: "A nossa equipa vai responder-lhe em menos de 24 horas úteis.",
    sendAnother: "ENVIAR OUTRA MENSAGEM",
  },
  mapa: {
    badge: "MAPA ESTRATÉGICO",
    title: "Integração da Rede Nacional",
    text: "Terminais estrategicamente distribuídos ao longo dos corredores EN100, EN120 e EN230, cobrindo os principais fluxos de mobilidade do país.",
    linha: "COBERTURA LOGÍSTICA: 4 PROVÍNCIAS // 25+ PONTOS",
  },
};
