export const rastreamentoContent = {
  subHeader: {
    telemetrySublabel: "TELEMETRIA SATELITAL GPS // V4.8",
    liveBadge: "LIVE DISPATCH",
    title: "Centro de Controlo & Radar de Operações",
    clockLabel: "HORA DE LUANDA (WAT)",
  },
  stats: [
    { label: "PONTUALIDADE HOJE", value: "98.4%" },
    { label: "FROTA EM CURSO", value: "64 UNID" },
    { label: "STATUS DO RADAR", value: "ATIVO 100%" },
  ],
  busca: {
    cornerRef: "DISPATCH DOC: 2026-AO-RADAR",
    badgeIcon: "terminal",
    badge: "MÓDULO DE INTERROGAÇÃO TELEMÁTICA",
    title: "Localizar Autocarro, Reserva ou Encomenda",
    paragraph: "Insira o código do seu bilhete emitido nas bilheteiras da Rosalina Express ou a carta de porte (AWB) da Rede Cargo Express para rastreio milimétrico em rota.",
    tabs: [
      { id: "passenger", label: "1. Rastrear Bilhete / Autocarro", icon: "directions_bus" },
      { id: "cargo", label: "2. Rastrear Carga (Rede Cargo AWB)", icon: "local_shipping" },
    ],
    passenger: {
      label: "Nº do Bilhete, Código de Reserva ou Prefixo da Viatura (ex: RE-014, BXP-8910)",
      labelIcon: "qr_code_scanner",
      placeholder: "Ex: RE-014 ou BIL-779841",
      btn: "Localizar no Radar",
      btnIcon: "radar",
      suggestionsLabel: "Sugestões rápidas:",
      suggestions: [
        "RE-014 (Luanda ➔ Benguela)",
        "RE-089 (Luanda ➔ Huambo)",
        "RE-105 (Benguela ➔ Lobito)",
      ],
    },
    cargo: {
      label: "Código da Guia de Transporte / Air Waybill Rodoviária (AWB)",
      labelIcon: "inventory_2",
      placeholder: "Ex: RX-9942-AO ou CG-44021",
      btn: "Verificar Carga",
      btnIcon: "package_2",
      suggestionsLabel: "Exemplos de manifesto:",
      suggestions: [
        "RX-9942-AO (Carga Seca Luanda)",
        "RX-8104-BN (Expresso Benguela)",
      ],
    },
  },
  radar: {
    sublabel: "MODO TÁTICO DE SATÉLITE",
    sublabelIcon: "satellite_alt",
    title: "Radar Rodoviário Nacional: Eixo Luanda ➔ Huambo",
    gpsStatus: "GPS LOCK: ESTÁVEL",
    pingStatus: "PING: 38ms",
    updateLabel: "ÚLTIMA ATUALIZAÇÃO:",
    corridor: "ROTA EN-100 / EN-260 CORREDOR SUL",
    markers: [
      { label: "0 KM", name: "LUANDA CENTRO" },
      { label: "180 KM", name: "PORTO AMBOIM" },
      { label: "350 KM", name: "SUMBE" },
      { label: "540 KM", name: "LOBITO" },
      { label: "620 KM", name: "BENGUELA" },
    ],
    selectedBus: { code: "RE-014", speed: "88 KM/H", position: 55 },
    fleet: [
      {
        status: "VEÍCULO SELECIONADO",
        statusCor: "primary",
        km: "KM 342",
        name: "RE-014 MARCOPOLO",
        route: "Luanda ➔ Benguela Expresso",
        speed: "VEL: 88 km/h",
        eta: "ETA: 1h 40m",
      },
      {
        status: "EM TRÂNSITO",
        statusCor: "tertiary",
        km: "KM 118",
        name: "RE-089 SCANIA K410",
        route: "Luanda ➔ Huambo Noturno",
        speed: "VEL: 82 km/h",
        eta: "ETA: 4h 15m",
      },
      {
        status: "APROXIMAÇÃO",
        statusCor: "secondary",
        km: "KM 594",
        name: "RE-105 VOLVO B11R",
        route: "Benguela ➔ Lobito Shuttle",
        speed: "VEL: 65 km/h",
        eta: "ETA: 22m",
      },
    ],
    coachOverlay: "UNIDADE RE-014 EM OPERAÇÃO REAL // AUTOESTRADA EN-100",
    sensorOverlay: "SENSOR TEMPERATURA: NORMAL",
    telemetry: {
      header: "TELEMETRIA RE-014",
      headerBadge: "SINAL FORTE",
      gaugeCor: "primary",
      gauges: [
        { label: "VELOCIDADE GPS", value: "88", unit: "KM/H", bar: 75 },
        { label: "CLIMATIZAÇÃO CABINE", value: "21.5", unit: "°C", note: "CONFORTO CLASSE A" },
        { label: "DISTÂNCIA RESTANTE", value: "278", unit: "KM", note: "DESTINO: BENGUELA" },
        { label: "PREVISÃO CHEGADA", value: "16:25", unit: "EST", note: "NO HORÁRIO" },
      ],
      driver: "MOTORISTA DE ESCALA:",
      driverName: "Cap. Mateus Ndala (ID: RO-4402)",
      assentos: "ASSENTOS OCUPADOS:",
      assentosValue: "48 / 52 Lugares (92%)",
      ultimoCheckpoint: "ÚLTIMO CHECKPOINT:",
      ultimoCheckpointValue: "Sumbe Sul - Km 340 (14:38)",
      proximaParagem: "PRÓXIMA PARAGEM TÉCNICA:",
      proximaParagemValue: "Posto Rosalina Canjala (40 min)",
    },
    timelineHeader: "TIMELINE DE DESPACHO E PONTOS DE CONTROLE",
    checkpoints: [
      { time: "PARTIDA TERMINAL LUANDA (07:30)", text: "Saída autorizada pelo despacho central no horário previsto.", future: false },
      { time: "POSTO FISCAL CABO LEDO (09:42)", text: "Conferência de passageiros e verificação de tacógrafo OK.", future: false },
      { time: "SUMBE TERMINAL DE APOIO (14:38)", text: "Paragem para refeição rápida e troca de condutores de apoio.", future: false },
      { time: "TERMINAL RODOVIÁRIO BENGUELA (16:25 PREV)", text: "Desembarque final de passageiros e entrega de bagagens registradas.", future: true },
    ],
  },
  horarios: {
    sublabel: "PAINEL ELETRÓNICO DE PARTIDAS EM TEMPO REAL",
    sublabelIcon: "departure_board",
    title: "Quadro de Embarque & Horários Interprovinciais",
    filters: ["Todos", "Luanda", "Benguela", "Huambo", "Lobito", "Viana / Voltas"],
    columns: ["LINHA / PREFIXO", "ORIGEM ➔ DESTINO", "VIA", "HORA PROG.", "ESTIMADA / STATUS", "CAIS / PLATAFORMA", "TIPO DE SERVIÇO", "AÇÃO"],
    rows: [
      {
        prefix: "RE-014",
        route: "Luanda ➔ Benguela",
        via: "Via Sumbe / Porto Amboim",
        hour: "15:00",
        status: "EMBARQUE IMEDIATO",
        statusCor: "primary",
        statusIcon: "alarm",
        cais: "CAIS 01",
        tipo: "Marcopolo G7 Executivo (Wi-Fi + AC)",
        action: "Ver Radar",
      },
      {
        prefix: "RE-089",
        route: "Luanda ➔ Huambo",
        via: "Direto Noturno / Dondo",
        hour: "16:30",
        status: "NO HORÁRIO",
        statusCor: "secondary",
        statusIcon: "check_circle",
        cais: "CAIS 03",
        tipo: "Scania K410 Leito Total",
        action: "Ver Radar",
      },
      {
        prefix: "RE-105",
        route: "Benguela ➔ Lobito",
        via: "Conexão Metropolitana Litoral",
        hour: "14:00",
        status: "EM TRÂNSITO (KM 594)",
        statusCor: "tertiary",
        statusIcon: "navigation",
        cais: "CAIS B2",
        tipo: "Volvo B11R Interurbano",
        action: "Ver Radar",
      },
      {
        prefix: "RE-003",
        route: "Huambo ➔ Luanda",
        via: "Expresso Planalto Central",
        hour: "14:15",
        status: "PORTAS FECHADAS",
        statusCor: "surface-container-highest",
        statusIcon: "lock",
        cais: "CAIS 05",
        tipo: "Marcopolo Paradiso 1200",
        action: "Ver Radar",
      },
      {
        prefix: "VOL-101",
        route: "Luanda Central ➔ Viana Km 30",
        via: "Rede Urbana Voltas - Frequência Alta",
        hour: "15:10",
        status: "PREV. 4 MIN",
        statusCor: "secondary",
        statusIcon: "schedule",
        cais: "PLAT. U1",
        tipo: "Frota Urbana Low-Floor Rosalina",
        action: "Ver Paragem",
      },
    ],
    legend: [
      { label: "Embarque Aberto", dot: "primary-container" },
      { label: "No Horário", dot: "secondary" },
      { label: "Em Estrada", dot: "tertiary" },
      { label: "Partida Efetuada", dot: "surface-dim" },
    ],
    syncLabel: "SINCRONIZAÇÃO AUTOMÁTICA VIA RÁDIO DISPATCH // CENTRAL HO CHI MINH",
  },
  voltas: {
    sublabel: "SERVIÇO METROPOLITANO ROSALINA EXPRESS",
    sublabelIcon: "directions_transit",
    title: "Rede \"Voltas\" - Monitorização Urbana em Tempo Real",
    paragraph: "Autocarros urbanos conectando os principais eixos habitacionais, terminais de transbordo e polos comerciais de Luanda e arredores com intervalos regulares.",
    freqBadge: "FREQUÊNCIA MÉDIA: 8-12 MIN",
    terminalOverlay: "TERMINAL CENTRAL DE VIANA // CAIS DE ALTA ROTAÇÃO",
    terminalFleet: "12 VEÍCULOS ALINHADOS",
    lines: [
      { code: "LINHA 101", cor: "primary-container", route: "Viana Km 30 ➔ Luanda Baixa", nextStop: "Próxima paragem: Estalagem", eta: "4 MIN RESTANTES", etaPulsing: true, occupancy: "Média (65%)", fleet: "8 Autocarros" },
      { code: "LINHA 102", cor: "tertiary", route: "Cacuaco ➔ Terminal Ho Chi Minh", nextStop: "Próxima paragem: São Paulo", eta: "9 MIN RESTANTES", etaPulsing: false, occupancy: "Alta (88%)", fleet: "6 Autocarros" },
      { code: "LINHA 103", cor: "secondary", route: "Benfica / Talatona ➔ Cidade Alta", nextStop: "Próxima paragem: Gamek", eta: "2 MIN RESTANTES", etaPulsing: true, occupancy: "Normal (45%)", fleet: "7 Autocarros" },
      { code: "LINHA 104", cor: "surface-container-highest", route: "Kilamba ➔ Aeroporto Internacional 4F", nextStop: "Próxima paragem: Camama", eta: "14 MIN RESTANTES", etaPulsing: false, occupancy: "Baixa (30%)", fleet: "5 Autocarros" },
    ],
  },
  suporte: {
    sublabel: "DESPACHO DE ATENDIMENTO AO PASSAGEIRO",
    sublabelIcon: "support_agent",
    title: "Dúvidas sobre o seu horário ou atraso operacional?",
    paragraph: "Nossos operadores de rota estão conectados 24 horas por dia para confirmar posições de viaturas, coordenar reagendamento de passagens ou acionar apoio para cargas prioritárias em toda Angola.",
    metrics: [
      { label: "RESPOSTA WHATSAPP", value: "< 3 MINUTOS" },
      { label: "REAGENDAMENTO", value: "GRÁTIS EM 2H" },
      { label: "CENTRAL TELEFÓNICA", value: "LINHA DIRETA" },
    ],
    ctas: [
      { label: "WhatsApp Operacional 24/7", icon: "chat", href: "https://wa.me/244923521224", cor: "primary-container" },
      { label: "Ligar: +244 923 521 224", icon: "phone_in_talk", href: "tel:+244923521224", cor: "surface-container-lowest" },
      { label: "Política de Atrasos & Reembolsos de Bilhetes", icon: "help_outline", href: "#", cor: "secondary" },
    ],
  },
};
