export const sobreContent = {
  subHeader: {
    breadcrumb: ["Início", "Institucional", "História do Grupo Rosalina"],
    ref: "REF: HIST-CORP-2026 // LIVRO BRANCO INSTITUCIONAL",
    coord: "COORD: 8°50'18\"S 13°14'04\"E",
    badge: "GRUPO EMPRESARIAL 100% ANGOLANO • FUNDAÇÃO: 2004 • SEDE: LUANDA",
    title: "Duas Décadas a Conectar Angola",
    subtitle: "A História e a Dimensão Estratégica do Grupo Rosalina Express",
    docTitle: "DOCUMENTO ESTRATÉGICO",
    docYears: "2004 - 2026",
    docText:
      "De uma pioneira operação de transportes interprovinciais a um conglomerado multissetorial de referência nacional em Transportes, Hotelaria, Restauração e Combustíveis.",
  },
  heroSede: {
    image:
      "https://lh3.googleusercontent.com/aida-public/AB6AXuA2LQQj8nB2SoG_r-PXvwsti8EXWChu6m63nrkcw_PmuGxQqnsq9DPAgGfIy8irKuMHHAQvV0W4AFBSfPKB4xstaPTd0AWqZIvi8aDRD6OC-Wv8YYJqjkuODX-fclQxoERi4GGh9c4Jo0SpWTdkcn_SSQRzHejXnnOBgIDA4PSnilcmywLDUDsnRhigBVenZDbu_lqzGRf0nbVvQUWi0sKPd2Yi4a1c50JAOrnwJXRQqkjXg-GM-LaEdg",
    imageHeader: "EDIFÍCIO SEDE CORPORATIVA & TERMINAL INTEGRADO",
    imageLoc: "LUANDA / AO",
    overlayLabel: "INFRAESTRUTURA DE COMANDO OPERACIONAL",
    overlayTitle: "Complexo Corporativo Rosalina Express — Luanda",
    tapeLeft: "AV. HO CHI MINH, CENTRAL RODOVIÁRIA",
    tapeRight: "STATUS OPERACIONAL: HUB CENTRAL 24/7",
    manifestBadge: "MANIFESTO DO GRUPO",
    manifestTitle:
      "Encurtar distâncias, garantir a circulação segura e impulsionar a economia angolana.",
    manifestText:
      "Com mais de duas décadas de compromisso inabalável com o povo e as empresas de Angola, o Grupo Rosalina consolidou-se como a espinha dorsal do transporte rodoviário e logística nacional, combinando bravura operacional com tecnologia de vanguarda.",
    stats: [
      { icon: "history_edu", label: "HISTÓRIA", value: "20+", text: "Anos de Operação Ininterrupta" },
      { icon: "hub", label: "CONECTIVIDADE", value: "04", text: "Províncias Estruturantes Integradas" },
      { icon: "domain_add", label: "CONGLOMERADO", value: "04", text: "Segmentos Económicos Ativos" },
      { icon: "pin_drop", label: "PRESENÇA", value: "25+", text: "Terminais, Parques e Balcões" },
    ],
  },
  timeline: {
    badge: "CRONOGRAMA DE OPERAÇÕES MILITARES E CIVIS",
    title: "Evolução Cronológica: Da Rota à Rede Integrada",
    note: "MARCOS DECISIVOS // 2004 ➔ 2026",
    marcos: [
      {
        ano: "ANO 2004",
        numBg: "primary",
        title: "As Origens da Rota Luanda ↔ Benguela",
        text: "Fundação pioneira sob contexto desafiante das vias rodoviárias pós-conflito. Estabelecimento da primeira operação regular entre a capital e o litoral com horários rígidos e compromisso absoluto de segurança.",
        despacho: "DESPACHO INAUGURAL: 12 AUTOCARROS",
        despachoCor: "primary",
        final: false,
      },
      {
        ano: "ANO 2011",
        numBg: "tertiary",
        title: "Planalto Central & Rede de Oficinas",
        text: "Expansão para Huambo e Lobito. Instalação de centros técnicos de apoio operacional em Sumbe e Canjala, assegurando assistência mecânica imediata aos veículos e conforto prioritário aos viajantes.",
        despacho: "ESTRUTURAÇÃO: OFICINAS PESADAS 24H",
        despachoCor: "tertiary",
        final: false,
      },
      {
        ano: "ANO 2017",
        numBg: "secondary",
        title: "Diversificação: O Grupo Multissetorial",
        text: "Consolidação corporativa em holding. O grupo alarga os investimentos para postos de abastecimento próprios, unidades hoteleiras executivas e restaurantes rodoviários de padrão sanitário internacional.",
        despacho: "CRIAÇÃO: GRUPO ROSALINA HOLDING",
        despachoCor: "secondary",
        final: false,
      },
      {
        ano: "ANO 2021",
        numBg: "tertiaryContainer",
        title: "Mobilidade Urbana: Sistema 'Voltas'",
        text: "Entrada decisiva no transporte metropolitano da capital de Luanda. Início das rotas integradas ligando Viana, Cacuaco, Cidade do Kilamba e a Baixa da Mutamba com tarifas populares e alta densidade de horários.",
        despacho: "COBERTURA URBANA: +50 MIL PASS/DIA",
        despachoCor: "primary",
        final: false,
      },
      {
        ano: "ANO 2026",
        numBg: "primaryContainer",
        title: "Telemetria Satelital & Logística Verde",
        text: "Rastreamento em tempo real via satélite de 100% da frota, modernização com veículos Scania e Mercedes-Benz de baixa emissão, emissão digital de bilhetes e controlo militar de velocidade.",
        despacho: "ESTADO ATUAL: DIGITALIZAÇÃO TOTAL",
        despachoCor: "primary",
        final: true,
      },
    ],
  },
  segmentos: {
    badge: "ARQUITETURA DE NEGÓCIOS INTEGRADA",
    title: "Os 4 Segmentos Empresariais",
    description:
      "Atuação multissetorial sincronizada, gerando valor estratégico, sustentabilidade financeira e soluções integradas de mobilidade e infraestrutura em Angola.",
    items: [
      {
        num: "SEGMENTO 01",
        headerBg: "primary",
        icon: "local_shipping",
        cat: "CORE BUSINESS",
        catCor: "primary",
        title: "Transportes & Logística Integrada",
        text: "Rede Express interprovincial de alta velocidade, Sistema de Transporte Urbano 'Voltas', Shuttles executivos para multinacionais e Despacho de Cargas diário porta-a-terminal.",
        list: [
          "Interurbano de Longo Curso",
          "Mobilidade Urbana Luanda",
          "Carga Expressa & Encomendas",
          "Frotas Dedicadas a Empresas",
        ],
        footerIcon: "verified",
        footer: "COBERTURA NACIONAL ATIVA",
      },
      {
        num: "SEGMENTO 02",
        headerBg: "tertiary",
        icon: "hotel",
        cat: "HOSPITALIDADE",
        catCor: "tertiary",
        title: "Hotelaria & Hospedagem Executiva",
        text: "Rede de alojamento e hotéis de trânsito em pontos nodais de Luanda e Benguela, proporcionando repouso com conforto e climatização para viajantes corporativos e equipas de logística.",
        list: [
          "Quartos Executivos Climatizados",
          "Localização Junto aos Terminais",
          "Segurança Privada 24 Horas",
          "Suporte a Tripulações Técnicas",
        ],
        footerIcon: "hotel_class",
        footer: "PADRÃO EXECUTIVO GARANTIDO",
      },
      {
        num: "SEGMENTO 03",
        headerBg: "secondary",
        icon: "restaurant",
        cat: "NUTRIÇÃO RODOVIÁRIA",
        catCor: "secondary",
        title: "Restauração & Gastronomia de Trânsito",
        text: "Restaurantes rodoviários modernos e lanchonetes expressas nos principais corredores de ligação, assegurando controle de higiene exemplar, culinária angolana e atendimento ágil.",
        list: [
          "Paragens Oficiais Higienizadas",
          "Refeições Rápidas & Buffet",
          "Catering para Viagens Expresso",
          "Auditoria Sanitária Permanente",
        ],
        footerIcon: "sanitizer",
        footer: "CERTIFICAÇÃO SANITÁRIA A1",
      },
      {
        num: "SEGMENTO 04",
        headerBg: "inverse",
        icon: "local_gas_station",
        cat: "ABASTECIMENTO",
        catCor: "surface",
        title: "Combustíveis & Suporte Mecânico",
        text: "Rede de postos de abastecimento equipados com combustíveis certificados, estações de lubrificação de alto rendimento e serviços de manutenção preventiva para frotas pesadas e viaturas ligeiras.",
        list: [
          "Postos Estratégicos na EN100",
          "Gasóleo & Gasolina Refinados",
          "Centro de Lubrificantes Shell/Total",
          "Atendimento a Frotas de Terceiros",
        ],
        footerIcon: "oil_barrel",
        footer: "CONTROLE RIGOROSO DE PUREZA",
      },
    ],
  },
  lideranca: {
    image:
      "https://lh3.googleusercontent.com/aida-public/AB6AXuCriJUqgYRZFWfaEUaDyFCLk0dHXr4u6WtWwC5YmQdY9b6_hNPVUef0xO2fvAdJNXWcIAimE2vULMjPQLohxOAiV92HIQfusNnWkukJoi60Awm0BirNyCF28bEZOvPtSHbHhjrPyVKIdy3y2ezKpJ3f5aaJjhUXr81oVZiVlt2o-FozdnlVA1ZetuKMh92ijb9lBqCiUzlckmQCyUP892KAK9aYs10yLYQsgARfuqkxns_Xoq0KMWMWYg",
    imageHeader: "GOVERNANÇA E DIRECÇÃO ESTRATÉGICA",
    imageTag: "CONSELHO 2026",
    overlay: "CAPITAL 100% NACIONAL",
    captionTitle: "Comité Executivo & Gestão de Operações de Tráfego",
    captionText:
      "Reunião de alinhamento tático na Sala de Comando Central, Luanda — supervisão dos corredores Norte-Sul e expansão das linhas urbanas.",
    cardTitle: "Liderança com Raízes em Angola e Visão Global",
    cardBadge: "COMPROMISSO DE RIGOR E TRANSPARÊNCIA",
    text: "O modelo de governação do Grupo Rosalina assenta na prestação de contas, compliance rigoroso e investimento contínuo nas pessoas. Com uma força de trabalho com mais de mil profissionais diretos, qualificamos continuamente motoristas profissionais, engenheiros mecânicos e gestores de frota.",
    cheks: ["Auditado Anualmente", "+1.000 Postos de Trabalho"],
    pilares: [
      {
        icon: "security",
        title: "1. Segurança & Rigor Militar",
        text: "Manutenção preventiva a cada 5.000 km, revisão de travagem e suspensão quinzenal e tolerância zero com imprudência na condução.",
      },
      {
        icon: "schedule",
        title: "2. Pontualidade Britânica em Angola",
        text: "Despacho automatizado e sincronizado por telemetria satelital, conferindo respeito incondicional ao tempo dos passageiros e clientes de carga.",
      },
      {
        icon: "volunteer_activism",
        title: "3. Impacto Social & Coesão Territorial",
        text: "Redução do isolamento das populações rurais, transporte urbano acessível a trabalhadores e apoio ativo ao escoamento agrícola no interior.",
      },
    ],
  },
  certificacoes: {
    label: "HOMOLOGAÇÃO & CONFORMIDADE REGULAMENTAR",
    title: "Certificações Oficiais & Padrões Internacionais",
    status: "STATUS: 100% REGULARIZADO",
    items: [
      {
        icon: "policy",
        cor: "primary",
        title: "MINTRANS",
        sub: "REPÚBLICA DE ANGOLA",
        text: "Licenciamento e homologação total para transporte coletivo interurbano e urbano concedida pelo Ministério dos Transportes.",
      },
      {
        icon: "verified_user",
        cor: "tertiary",
        title: "DTSER // POLÍCIA",
        sub: "SEGURANÇA RODOVIÁRIA",
        text: "Frota 100% inspecionada pela Direcção de Trânsito e Segurança Rodoviária com tacógrafos e limitadores certificados.",
      },
      {
        icon: "eco",
        cor: "secondary",
        title: "EURO 5 / EURO 6",
        sub: "GESTÃO DE EMISSÕES",
        text: "Programa de redução ativa de pegada de carbono, renovação de motorizações e descarte responsável de lubrificantes.",
      },
      {
        icon: "sentiment_very_satisfied",
        cor: "primary",
        title: "QUALIDADE AO CLIENTE",
        sub: "ÍNDICE DE CONFIANÇA",
        text: "Mais de 96% de taxa de satisfação e pontualidade auditada nos serviços de longo curso Luanda ↔ Benguela ↔ Huambo.",
      },
    ],
  },
  cta: {
    badge: "PARCERIAS & EXPANSÃO NACIONAL",
    sideLabel: "CANAL DIRECTO COM A ADMINISTRAÇÃO",
    title: "Faça Parte do Futuro da Mobilidade em Angola",
    text: "Seja como passageiro em viagens confortáveis, operador logístico ou como parceiro corporativo em frotas dedicadas e infraestruturas, o Grupo Rosalina tem a estrutura pronta para mover a sua empresa.",
    btn1: "FALAR COM A ADMINISTRAÇÃO",
    btn2: "CONSULTAR NOSSOS SERVIÇOS",
    line: "LINHA CORPORATIVA: +244 923 521 224",
  },
};
